#!/bin/bash
## manjaroiso-backup : Backup your system using manajroiso
#  Copyright (C) 2014 Aaditya Bagga (aaditya_gnulinux@zoho.com)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  any later version.
#
#  This program is distributed WITHOUT ANY WARRANTY;
#  without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

#set -e  # Exit on errors

# Set mode. 
# 0 = backup, 1 = generic
#mode=0
#echo "In mode $mode"

# Set config.
# default = net. Options include xfce, kde, openbox, etc.
config=net
Config=Net  # The packages file have the first letter as capital.
echo "Using config $config"

# (Re)install manjaroiso
echo "Installing manjaroiso..."
sudo pacman -S --needed manjaroiso manjaroiso-profiles

# Copy a manjarosio profile to the home folder
if [ ! -d ~/manjaroiso/backup/$config ]; then
	echo "Copying profiles..."
	mkdir -p ~/manjaroiso/backup
	rsync -aAXv /usr/share/manjaroiso/configs/shared ~/manjaroiso/backup/
	rsync -aAXv /usr/share/manjaroiso/configs/$config ~/manjaroiso/backup/
fi

# Handle installed packages
cd ~/manjaroiso/backup/$config

cp Packages Packages.bak  # Make backup of the default packages
cp Packages-Xorg Packages-Xorg.bak  # Make backup of the default xorg packages
cp Packages-$Config Packages-$Config.bak  # Make backup of the default DE packages

#if [ $mode -eq 1 ]; then
	# do nothing
#	echo
#else
#	echo "bash" > Packages-Xorg  # Dummy package for Xorg
#fi

echo "Saving package list..."
pacman -Qqen > Packages-$Config  # All explicitly installed packages as DE packages


# Handle home folder
echo "Copying home folder..."
# Copy contents of home folder to installed system overlay
rsync -aAXv --max-size=5M --delete --exclude={"/home/*/.thumbnails/*","/home/*/.cache/*","/home/*/.local/share/Trash/*","/home/aaditya/DataLinux/*","/home/aaditya/builds/*","/home/aaditya/manjaroiso/*","/home/*/.wine*"} /home overlay/  

# Handle etc folder
echo "Copying etc folder..."
# Copy contents of etc folder to installed system overlay
rsync -aAXv --delete /etc overlay/  

# Make ISO
echo "Building ISO..."
sudo buildiso
