#!/bin/bash
#Script to reverse the entered number

if [ ! $1 ]; then
	echo "Invalid number of arguments"
	exit 1
fi

num=$1
revno=0

while [ $num -gt 0 ]
do
	let rem=$num%10
	let revno=`expr $revno \* 10`+$rem
	let num=$num/10
done

echo "Reversed number is $revno"
exit 0	
