#!/bin/bash
list=$(xinput --list | grep -i -e 'mouse' -e 'OM')
if [ ${#list} -eq 0 ]; then
    exec `synclient touchpadoff=0`
    notify-send "No USB mouse found" "Your touchpad is set to ON"
else
    exec  `synclient touchpadoff=1`
    notify-send "USB mouse plugged" "Your touchpad is now turned OFF"
fi
